config/routes.rb
Rails.application.routes.draw do
require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'homes#show'
  post 'set_time', to: 'homes#set_time'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    get 'login', to: 'sessions#new'
    get 'logout', to: 'sessions#logout'
    resources :sessions
    resources :rooms
    resources :room_types
    resources :landing_images do
      get :resize, on: :collection
    end
    resources :tours
    resources :review_images

    resource :main
    resources :contacts, only: :index do
      post :upload, on: :collection
    end

    resource :amenities
    resources :promotions
  end
  resource :home, only: :show do
    get :show2, on: :member
    get :test, on: :member
  end

  resources :rooms, only: [:show, :index]
  resource :paypal, only: :show do
    get :success, on: :member
    get :failed, on: :member
  end

  resources :amenities, only: :index
  resources :availables, only: :create
  resources :tours, only: [:index, :show]
  resources :promotions, only: :show

end

app/controllers/admin/room_types_controller.rb
class Admin::RoomTypesController < AdminController
  def index

  end

  def new
    @room_type = RoomType.new
    @room_type.room_images.build
    flash[:success] = 'Created successfully'
  end

  def edit
    @room_type = RoomType.friendly.find(params[:id])
  end

  def create
    @room_type = RoomType.new(room_type_params)
    return redirect_after_save
  end

  def update
    @room_type = RoomType.friendly.find(params[:id])
    @room_type.assign_attributes(room_type_params)
    flash[:success] = 'Updated successfully'
    return redirect_after_save
  end

  def redirect_after_save
    if @room_type.save
      redirect_to action: :edit
    else
      flash.now[:danger] = @room_type.errors.full_messages.join('. ')
      render :new
    end
  end

  private
  def room_type_params
    params.require(:room_type).permit(:name, :title, :description, :short_description, :size, :favourite, :fake_features, :price, :capacity, :init_price, :bed_type, :position, room_images_attributes: [:id, :image, :_destroy, :primary])
  end
end

app/views/admin/room_types/_form.html.haml
= form_for([:admin, @room_type], html: {class: 'form-horizontal center'}) do |f|
  .form-group
    = f.label :name, class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :total, 'Capacity', class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :capacity, class: 'form-control'
  .form-group
    = f.label :bed_type, class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :bed_type, class: 'form-control'
  .form-group
    = f.label :size, class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :size, class: 'form-control'
  .form-group
    = f.label :features, 'Features', class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :fake_features, class: 'form-control', value: f.object.features.join(', ')
  .form-group
    = f.label :title, 'Title', class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :position, class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :position, class: 'form-control'
  .form-group
    = f.label :short_description, class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :short_description, class: 'form-control'
  .form-group
    = f.label :description, class: "col-md-2 control-label"
    .col-md-10
      = f.text_area :description, class: 'form-control'
  .form-group
    = f.label 'Initial Price', class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :init_price, class: 'form-control'
  .form-group
    = f.label 'Price', class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :price, class: 'form-control'
  .form-group
    = f.label 'Favourite', class: "col-md-2 control-label"
    .col-md-10
      = f.check_box :favourite
  .form-group
    = f.label 'Images', class: "col-md-2 control-label"
    %h3.small (should be 356x228)
    .col-md-10.col-md-offset-2
      = f.fields_for :room_images do |image_form|
        = render 'room_image_fields', f: image_form
      .links
        = link_to_add_association '+', f, :room_images, class: 'btn btn-info'
  %br
  .actions.col-md-2.col-md-offset-2
    = f.submit class: 'btn btn-success'

app/views/admin/room_types/_room_capacity_fields.html.haml
.row.nested-fields
  .field.col-sm-3
    = f.text_field :capacity, placeholder: 'Capacity', class: 'form-control'
  .field.col-sm-3
    = f.text_field :start_date, placeholder: 'Start Date', class: 'form-control', 'data-provide' => :datepicker, 'data-date-format' => 'yyyy-M-dd', value: f.object.start_date.try(:strftime, '%Y-%b-%d')
  .field.col-sm-3
    = f.text_field :end_date, placeholder: 'End Date', class: 'form-control', 'data-provide' => :datepicker, 'data-date-format' => 'yyyy-M-dd', value: f.object.end_date.try(:strftime, '%Y-%b-%d')
  .col-sm-3
    = link_to_remove_association 'X', f, class: 'btn btn-danger'

app/views/admin/room_types/_room_image_fields.html.haml
.row.room-image-form.nested-fields
  .field.col-sm-8
    = image_tag f.object.image.url(:medium) if f.object.image?
    = f.file_field :image
  .col-sm-2
    = f.check_box :primary
    = f.label :primary
  .col-sm-2
    = link_to_remove_association 'X', f, class: 'btn btn-danger'

app/views/admin/room_types/_room_price_fields.html.haml
- if f.object.expired?
  .row.nested-fields.room-price-form
    .field.col-sm-3
      = f.text_field :price, placeholder: 'Price', class: 'form-control', readonly: true
    .field.col-sm-3
      = f.text_field :start_date, value: f.object.start_date.try(:strftime, '%Y-%b-%d'), class: 'form-control', readonly: true
    .field.col-sm-3
      = f.text_field :end_date, value: f.object.end_date.try(:strftime, '%Y-%b-%d'), class: 'form-control', readonly: true
    .col-sm-3
- else
  .row.nested-fields.room-price-form
    .field.col-sm-3
      = f.text_field :price, placeholder: 'Price', class: 'form-control'
    .field.col-sm-3
      = f.text_field :start_date, placeholder: 'Start Date', class: 'form-control', 'data-provide' => :datepicker, 'data-date-format' => 'yyyy-M-dd', value: f.object.start_date.try(:strftime, '%Y-%b-%d')
    .field.col-sm-3
      = f.text_field :end_date, placeholder: 'End Date', class: 'form-control', 'data-provide' => :datepicker, 'data-date-format' => 'yyyy-M-dd', value: f.object.end_date.try(:strftime, '%Y-%b-%d')
    .col-sm-3
      = link_to_remove_association 'X', f, class: 'btn btn-danger'

app/views/admin/room_types/edit.html.haml
.container
  %h1.text-center Edit Room Type
  = render 'shared/flash'
  = render 'form'

app/views/admin/room_types/index.html.haml
%h1.text-center Admin Room Types
.container-fluid
  = render 'shared/flash'
  .row
    %h3.col-md-3.text-center
      Name
    %h3.col-md-2.text-center
      Price
    %h3.col-md-2.text-center
      Capacity
    %h3.col-md-2.text-center
      Remaining Room
      .small (today)
    %h3.col-md-3.text-center
      Actions
  - RoomType.find_each do |room_type|
    .row
      .col-md-3.text-center
        = room_type.name
      .col-md-2.text-center
        = "$ #{room_type.price}"
      .col-md-2.text-center.bg-success
        = room_type.capacity
      .col-md-3.text-center
        = link_to 'Delete', admin_room_type_path(room_type), method: :delete, data: {confirm: 'Are you sure ?'}
        = link_to 'Edit', edit_admin_room_type_path(room_type)
  .text-center
    %br
    = link_to 'Add New Room Type', new_admin_room_type_path, class: 'btn btn-success'

app/views/admin/room_types/new.html.haml
.container
  %h1.text-center New Room Type
  = render 'shared/flash'
  = render 'form'