config/routes.rb
Rails.application.routes.draw do
require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'homes#show'
  post 'set_time', to: 'homes#set_time'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    get 'login', to: 'sessions#new'
    get 'logout', to: 'sessions#logout'
    resources :sessions
    resources :rooms
    resources :room_types
    resources :landing_images do
      get :resize, on: :collection
    end
    resources :tours
    resources :review_images

    resource :main
    resources :contacts, only: :index do
      post :upload, on: :collection
    end

    resource :amenities
    resources :promotions
  end
  resource :home, only: :show do
    get :show2, on: :member
    get :test, on: :member
  end

  resources :rooms, only: [:show, :index]
  resource :paypal, only: :show do
    get :success, on: :member
    get :failed, on: :member
  end

  resources :amenities, only: :index
  resources :availables, only: :create
  resources :tours, only: [:index, :show]
  resources :promotions, only: :show

end

app/models/tour.rb
class Tour < ApplicationRecord
  extend FriendlyId
  acts_as_taggable
  has_many :tour_images, dependent: :destroy
  friendly_id :name, use: :slugged
  accepts_nested_attributes_for :tour_images, allow_destroy: true, reject_if: :all_blank
  PRIVATE_GROUP = ['2', '3 - 4', '5 - 7', '8 - 9', '10 +']

  def class_tag_list
    tag_list.map(&:downcase).map{|e| e.gsub(' ', '_')}.join(' ')
  end
  private
  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end

end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < AdminController
  def index
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(tour_params)
    if @tour.save
      redirect_to action: :index
    else
      flash.now[:danger] = @tour.errors.full_messages.join('. ')
      render :new
    end
  end

  def edit
    @tour = Tour.friendly.find params[:id]
  end

  def update
    @tour = Tour.friendly.find params[:id]
    if @tour.update_attributes(tour_params)
      redirect_to action: :index
    else
      flash.now[:danger] = @tour.errors.full_messages.join('. ')
      render :edit
    end
  end

  def destroy
    @tour = Tour.friendly.find params[:id]
    @tour.destroy
    redirect_to action: :index
  end

  private
  def tour_params
    params.require(:tour).permit(:group, :title, :tag_list, :name, :start_time, :end_time, :price, :included, :short_description, private_tour_pricing: [], tour_images_attributes: [:id, :image, :description, :primary, :_destroy])
  end

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  layout 'application'
  def index
    if params[:filter].present?
      @tours = Tour.tagged_with params[:filter]
    else
      @tours = Tour.all
    end
  end

  def show
    @tour = Tour.friendly.find params[:id]
  end

end

app/views/admin/tours/_form.html.haml
= form_for([:admin, @tour], html: {class: 'form-horizontal center'}) do |f|
  .form-group
    = f.label :name, class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label 'Short Title', class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :group, class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :group, class: 'form-control'
  .form-group
    = f.label :start_time, 'Start', class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :start_time, class: 'form-control'
  .form-group
    = f.label :end_time, 'Return', class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :end_time, class: 'form-control'
  .form-group
    = f.label :short_description, class: "col-md-2 control-label"
    .col-md-10
      = f.text_area :short_description, class: 'form-control text-editor'
  .form-group
    = f.label 'Price', class: "col-md-2 control-label"
    .col-md-10
      = f.text_field :price, class: 'form-control'
  .form-group
    = f.label 'Include:', class: "col-md-2 control-label"
    .col-md-10
      = f.text_area :included, class: 'form-control'

  .form-group
    = f.label :private_tour_pricing, class: 'col-md-2 control-label'
    .col-md-10
      - Tour::PRIVATE_GROUP.each do |private_group|
        .text-center.col-md-2= private_group
    .col-md-10
      - 5.times do |i|
        .col-md-2
          = f.text_field :private_tour_pricing, class: 'form-control', name: 'tour[private_tour_pricing][]', value: @tour.private_tour_pricing.at(i).to_f > 0 ? @tour.private_tour_pricing.at(i) : nil
  .form-group
    = f.label 'Tags', class: "col-md-2 control-label"
    .col-md-10
      = f.text_area :tag_list, class: 'form-control'
  .form-group
    = f.label 'Images & Descriptions', class: "col-md-2 control-label"
    %h3.small (should be 356x228)
    .col-md-10.col-md-offset-2
      = f.fields_for :tour_images do |image_form|
        = render 'tour_image_fields', f: image_form
      .links
        = link_to_add_association '+', f, :tour_images, class: 'btn btn-info'
  %br
  .actions.col-md-2.col-md-offset-2
    = f.submit class: 'btn btn-success'
:javascript
  $(document).on('ready', function(){
    $('.text-editor').wysihtml5({
    toolbar:{
      "font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
      "emphasis": true, //Italics, bold, etc. Default true
      "lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
      "blockquote": false,
      "html": true, //Button which allows you to edit the generated HTML. Default false
      "link": true, //Button to insert a link. Default true
      "image": false, //Button to insert an image. Default true,
      "color": true //Button to change color of font  
      }
    });
  });

app/views/admin/tours/_tour_image_fields.html.haml
.row.room-image-form.nested-fields
  .col-sm-10
    = f.text_area :description, class: 'form-control text-editor', rows: 5
  .field.col-sm-10
    = image_tag f.object.image.url, height: 100 if f.object.image?
    = f.file_field :image
  .col-sm-1
    = f.check_box :primary
    = f.label :primary
  .col-sm-1
    = link_to_remove_association 'X', f, class: 'btn btn-danger'

app/views/admin/tours/edit.html.haml
.container
  %h1.text-center Edit Tour
  = render 'shared/flash'
  = render 'form'

app/views/admin/tours/index.html.haml
%h1.text-center Admin Tours
.container-fluid
  = render 'shared/flash'
  .row
    %h3.col-md-3.text-center
      Name
    %h3.col-md-2.text-center
      Start
    %h3.col-md-2.text-center
      Return
    %h3.col-md-2.text-center
      Price
    %h3.col-md-3.text-center

  - Tour.find_each do |tour|
    .row
      .col-md-3.text-center
        = tour.name
      .col-md-2.text-center
        = tour.start_time
      .col-md-2.text-center.bg-success
        = tour.end_time
      .col-md-2.text-center
        = "$ #{tour.price}"
      .col-md-3.text-center
        = link_to 'Delete', admin_tour_path(tour), method: :delete, data: {confirm: 'Are you sure ?'}
        = link_to 'Edit', edit_admin_tour_path(tour)
  .text-center
    %br
    = link_to 'Add New Room Type', new_admin_tour_path, class: 'btn btn-success'

app/views/admin/tours/new.html.haml
.container
  %h1.text-center New Tour
  = render 'shared/flash'
  = render 'form'