config/routes.rb
Rails.application.routes.draw do
require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'homes#show'
  post 'set_time', to: 'homes#set_time'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    get 'login', to: 'sessions#new'
    get 'logout', to: 'sessions#logout'
    resources :sessions
    resources :rooms
    resources :room_types
    resources :landing_images do
      get :resize, on: :collection
    end
    resources :tours
    resources :review_images

    resource :main
    resources :contacts, only: :index do
      post :upload, on: :collection
    end

    resource :amenities
    resources :promotions
  end
  resource :home, only: :show do
    get :show2, on: :member
    get :test, on: :member
  end

  resources :rooms, only: [:show, :index]
  resource :paypal, only: :show do
    get :success, on: :member
    get :failed, on: :member
  end

  resources :amenities, only: :index
  resources :availables, only: :create
  resources :tours, only: [:index, :show]
  resources :promotions, only: :show

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_uniqueness_of :email
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
end

app/models/item_reservation.rb
class ItemReservation < ApplicationRecord
  belongs_to :reservable, polymorphic: true
  belongs_to :reservation, optional: true

  before_create :set_amount_and_price

  def set_amount_and_price
    self.amount = ReservablePricing.new(reservable).amount
    self.price = self.amount * (self.quantity || 1)
  end

end

app/models/landing_image.rb
class LandingImage < ApplicationRecord
  has_attached_file :image, styles: { thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/paypal_transaction.rb
class PaypalTransaction < ApplicationRecord
  belongs_to :reservation
  def self.available_for_token finding_token
    PaypalTransaction.find_by(transaction_id: nil, token: finding_token)
  end
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  include FriendlyId
  friendly_id :name, use: :slugged
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  scope :published, -> { where(published: true) }

  def discount
    if percentage_off.present?
      "#{percentage_off}%"
    else
      amount_off
      "$#{percentage_off}"
    end
  end
  private
  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end
end

app/models/remaining.rb
class Remaining < ApplicationRecord
  belongs_to :room_type
  validates :date, presence: true
  validates :room_type_id, uniqueness: { scope: :date }
  validates :quantity_left, numericality: { greater_than_or_equal_to: 0 }
  def initialize_quantity_left(quantity)
    update_attributes!(quantity_left: room_type.quantity - quantity)
  end

  def reduce_quantity_left(quantity)
    update_attributes!(quantity_left: quantity_left - quantity)
  rescue ActiveRecord::StaleObjectError
    reload
    retry
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  has_many :item_reservations, dependent: :destroy
  accepts_nested_attributes_for :item_reservations
  validates_presence_of :start_date, :end_date

  after_create :compute_sum_items_price

  def compute_sum_items_price
    self.price = item_reservations.map{|item| item.price.to_f}.sum
  end
end

app/models/review_image.rb
class ReviewImage < ApplicationRecord
  has_attached_file :image, styles: { thumb: "200x200"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :room_type
  validates :number, uniqueness: true, presence: true
end

app/models/room_image.rb
class RoomImage < ApplicationRecord
  belongs_to :room_type, optional: true

  has_attached_file :image, styles: { medium: '800x504>', thumb: "356x228>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  scope :primary, -> { where(primary: true).first || first}
end

app/models/room_promotion.rb
class RoomPromotion < ApplicationRecord
  belongs_to :room_type
  validates_presence_of :start_date, :end_date

  validate :percentage_or_amount_be_present

  def percentage_or_amount_be_present
    errors.add(:base, 'Percentage or Amount should be present') if [ percentage.to_i, amount.to_i ].max == 0
  end

  def discount_price
    if percentage.to_i > 0
      room_type.price * ( percentage/100.0 )
    else
      amount.to_i
    end
  end
end

app/models/room_type.rb
class RoomType < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  attr_accessor :fake_features
  validates :name, uniqueness: true, presence: true
  has_many :rooms
  has_many :room_images, dependent: :destroy
  has_many :room_promotions, dependent: :destroy
  has_many :item_reservations, as: :reservable
  has_many :remainings, dependent: :destroy
  has_one :active_room_promotion,  ->{ where('start_date <= :today AND end_date >= :today', today: Date.today) }, class_name: 'RoomPromotion'

  accepts_nested_attributes_for :room_images, allow_destroy: true, reject_if: :all_blank
  scope :favourite, -> { where(favourite: true) }
  before_save :set_features, if: :fake_features
  def set_features
    self.features = []
    fake_features.split(',').each do |feature|
      self.features << feature.strip
    end
  end

  def dormitory?
    name.downcase =~ /dorm/
  end

  private
  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end

end

app/models/setting.rb
class Setting < ApplicationRecord
  def self.last_book_time= value
    last_book_time = Setting.find_or_create_by(name: 'last_book_time')
    last_book_time.update_attributes value: value.to_i
  end

  def self.last_book_time
    last_book_time = Setting.find_or_create_by(name: 'last_book_time')
    last_book_time.update_attributes(value: Time.now.to_i) unless last_book_time.value.to_i > 0
    Time.at(last_book_time.value.to_i) > 12.hours.ago ? Time.at(last_book_time.value.to_i) : 12.hours.ago
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  extend FriendlyId
  acts_as_taggable
  has_many :tour_images, dependent: :destroy
  friendly_id :name, use: :slugged
  accepts_nested_attributes_for :tour_images, allow_destroy: true, reject_if: :all_blank
  PRIVATE_GROUP = ['2', '3 - 4', '5 - 7', '8 - 9', '10 +']

  def class_tag_list
    tag_list.map(&:downcase).map{|e| e.gsub(' ', '_')}.join(' ')
  end
  private
  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end

end

app/models/tour_image.rb
class TourImage < ApplicationRecord
  belongs_to :tour
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  scope :primary, -> { where(primary: true).first || first}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook, :google_oauth2, :twitter]
  has_many :identities, dependent: :destroy
  def self.from_omniauth auth
    user = User.find_or_initialize_by(email: auth['info']['email'])
    user.update_attributes(password: SecureRandom.hex(8), name: auth['info']['name']) unless user.persisted?
    user.identities.find_or_create_by(provider: auth.provider, uid: auth.uid.to_s) if user.persisted?
    return user
  end

end

app/helpers/homes_helper.rb
module HomesHelper
  def price_formatter price
    price.to_s.remove(/\.0|0+$/)
  end
end

app/views/results/_result.html.haml
.row.search-shadow-box.vertical-center
  .col-sm-4.search-item
    = image_tag RoomType.first.room_images.first.image, class: 'img-responsive'
  .col-sm-4.search-item
    .h3.room-title= RoomType.first.name
    %p= RoomType.first.description
    .row
      - RoomType.first.features.each_slice(3).each do |arr_feature|
        .col-sm-6
          %ul.list-unstyled.feature-search-result
            - arr_feature.each do |feature|
              %li
                %i.fa.fa-check-circle.color-blue
                = feature
    .last-book
      Last Booked: 8 hours ago
    .today-book.bold
      Today's Books: 17
  .col-sm-4.search-item
    .h3.deal-title
      Deals for you
      %del.old-price ($1400)
    .row.vertical-center.pricing
      .col-xs-6.bold
        No Refundable:
      .col-xs-6
        .price
          .btn.btn-primary
            %span $1000
          .saving
            = "- 40%"

app/views/shared/_amenities.html.haml
%section.usp.mt50.hidden-xs.hidden-sm
  .container
    .row
      .col-sm-12
        %h2.lined-heading
          %span Amenities
      .col-sm-2.bounceIn.appear.animated{"data-start" => "0"}
        %a{href: '/amenities'}
          .box-icon
            .circle
              %i.fa.fa-cutlery.fa-large.fa-2x
            %p Breakfast Included
      .col-sm-2.bounceIn.appear.animated{"data-start" => "400"}
        %a{href: '/amenities'}
          .box-icon
            .circle
              %i.fa.fa-credit-card.fa-lg.fa-2x
            %p Available 24/7
      .col-sm-2.bounceIn.appear.animated{"data-start" => "800"}
        %a{href: '/amenities'}
          .box-icon
            .circle
              %i.fa.fa-bus.fa-lg.fa-2x
            %p Transportation service
      .col-sm-2.bounceIn.appear.animated{"data-start" => "1200"}
        %a{href: '/amenities'}
          .box-icon
            .circle
              %i.fa.fa-car.fa-lg.fa-2x
            %p Public parking is available
      .col-sm-2.bounceIn.appear.animated{"data-start" => "1200"}
        %a{href: '/amenities'}
          .box-icon
            .circle
              %i.fa.fa-wifi.fa-lg.fa-2x
            %p Wifi is available in all areas
      .col-sm-2.bounceIn.appear.animated{"data-start" => "1200"}
        %a{href: '/amenities'}
          .box-icon
            .circle
              %i.fa.fa-briefcase.fa-lg.fa-2x
            %p Business center
    -# .col-sm-6.col-sm-offset-3.text-center.mt20
    -#   %a{href: '/amenities'}
    -#     .text-center.black-color VIEW ALL
%section.usp.mt50.visible-xs.visible-sm
  .container
    .row
      .col-sm-12
        %h2.lined-heading
          %span Amenities
      .col-xs-12
        .col-xs-2.bounceIn.appear.animated{"data-start" => "0"}
          %a{href: '/amenities'}
            .box-icon
              .circle
                %i.fa.fa-cutlery.fa-large.fa-2x
        .col-xs-2.bounceIn.appear.animated{"data-start" => "400"}
          %a{href: '/amenities'}
            .box-icon
              .circle
                %i.fa.fa-credit-card.fa-lg.fa-2x
        .col-xs-2.bounceIn.appear.animated{"data-start" => "800"}
          %a{href: '/amenities'}
            .box-icon
              .circle
                %i.fa.fa-bus.fa-lg.fa-2x
        .col-xs-2.bounceIn.appear.animated{"data-start" => "1200"}
          %a{href: '/amenities'}
            .box-icon
              .circle
                %i.fa.fa-car.fa-lg.fa-2x
        .col-xs-2.bounceIn.appear.animated{"data-start" => "1200"}
          %a{href: '/amenities'}
            .box-icon
              .circle
                %i.fa.fa-wifi.fa-lg.fa-2x
        .col-xs-2.bounceIn.appear.animated{"data-start" => "1200"}
          %a{href: '/amenities'}
            .box-icon
              .circle
                %i.fa.fa-briefcase.fa-lg.fa-2x
    -# .col-sm-6.col-sm-offset-3.text-center.mt20
    -#   %a{href: '/amenities'}
    -#     .text-center.black-color VIEW ALL

app/views/shared/_call_to_action.html.haml
%section#call-to-action.mt100
  .container
    .row.blur
      .text-center
        %h1 THE BLUE RIVER HOTEL
        %h3 We pursuit the satisfaction

app/views/shared/_flash.html.haml
- flash.each do |key, value|
  %div{class: "alert alert-#{key}"} 
    = value

app/views/shared/_footer.html.haml
%footer.grad
  .container
    .row
      .col-md-3.col-sm-3
        %h4 About Blue River Hotel
        %p
          Our hotel is right in the center of the district 1, Ho Chi Minh City, Vietnam.
          %br/
          All of our rooms are well-designed for your comfortable and satisfaction.
          %br/
          Our staffs are always available 24/7 for serving all your needs.
      .col-md-6.col-sm-6
        %h4.text-center Location
        = link_to 'https://www.google.com/maps/dir//blue+river+hotel+1' do
          = image_tag 'location.png', alt: 'Google Map of Blue River Hotel', width: '100%'
      .col-md-3.col-sm-3
        %h4.text-center Address
        %address
          %strong The Blue River Hotel
          %br/
          283/2C Phạm Ngu Lao
          %br/
          District 1, Ho Chi Minh City, Vietnam
          %br/
          %abbr{:title => "Phone"} Phone:
          %a{:href => "tel:+84838376483"} (+84 8) 3837 6483
          %br/
          %abbr{:title => "Email"} Email:
          %a{:href => "mailto:blriverhotel@gmail.com"} blriverhotel@gmail.com
          %br/
          %abbr{:title => "Website"} Website:
          %a{:href => "https://blriverhotel.com"} https://blriverhotel.com
          %br/
          .pull-left
            %a{href: 'https://www.tripadvisor.com/Hotel_Review-g293925-d676046-Reviews-Blue_River_Hotel-Ho_Chi_Minh_City.html'}
              .fa.fa-tripadvisor.social-btn.white-color
            %a{href: 'https://www.facebook.com/blueriverphamngulao/?notif_t=page_fan&notif_id=1496982273070191'}
              .fa.fa-facebook.social-btn.white-color
  -# .footer-bottom#footer-bottom-grad
  -#   .container
  -#     .row
  -#       .col-xs-6 © #{Time.now.year} BlueRiverHotel All Rights Reserved
  -#       .col-xs-6

app/views/shared/_gallery.html.haml
%section.gallery-slider.mt100
  .container
    .row
      .col-md-12
        %h2.lined-heading
          %span Gallery
  #owl-gallery.owl-carousel
    - RoomImage.find_each do |room_image|
      .item
        %a{href: room_image.image.url(:medium), 'data-rel' => 'prettyPhoto[gallery1]'}
          = image_tag room_image.image.url(:medium), alt: room_image.room_type.name || 'Image'
          %i.fa.fa-search

app/views/shared/_guest_reservation_form.html.haml
%section#reservation-form
  .container
    .row
      .col-md-12
        = form_for :available, url: availables_path, html: { class: 'form-inline reservation-horizontal clearfix', id: :reservationform }do |f|
          #message
          / Error message display
          .row
            .col-sm-3
              .form-group
                %label{:for => "email"} Email
                .popover-icon{"data-container" => "body", "data-content" => "Vivamus sagittis lacus vel augue laoreet rutrum faucibus.", "data-placement" => "right", "data-toggle" => "popover", "data-trigger" => "hover"}
                  %i.fa.fa-info-circle.fa-lg
                = f.text_field :email, class: 'form-control', placeholder: 'Type your email here', id: :email
            .col-sm-2
              .form-group
                %label{:for => "room"} Room Type
                .popover-icon{"data-container" => "body", "data-content" => "Vivamus sagittis lacus vel augue laoreet rutrum faucibus.", "data-placement" => "right", "data-toggle" => "popover", "data-trigger" => "hover"}
                  %i.fa.fa-info-circle.fa-lg
                = f.select :room_type_id, RoomType.pluck(:name, :id),{ selected: params[:room_type]}, class: 'form-control', id: :room, name: :room_type_id
            .col-sm-2
              .form-group
                %label{:for => "checkin"} Check-in
                .popover-icon{"data-container" => "body", "data-content" => "Check-In is from 11:00", "data-placement" => "right", "data-toggle" => "popover", "data-trigger" => "hover"}
                  %i.fa.fa-info-circle.fa-lg
                %i.fa.fa-calendar.infield
                %input#checkin.form-control{:name => "start_date", :placeholder => "Check-in", :type => "text", :value => "", 'data-provide' => 'datepicker', 'data-date-format' => 'yyyy-M-dd', value: params[:start_date]}/
            .col-sm-2
              .form-group
                %label{:for => "checkout"} Check-out
                .popover-icon{"data-container" => "body", "data-content" => "Check-out is from 12:00", "data-placement" => "right", "data-toggle" => "popover", "data-trigger" => "hover"}
                  %i.fa.fa-info-circle.fa-lg
                %i.fa.fa-calendar.infield
                %input#checkout.form-control{:name => "end_date", :placeholder => "Check-out", :type => "text", :value => "", 'data-provide' => 'datepicker', 'data-date-format' => 'yyyy-M-dd', value: params[:start_date]}/
            .col-sm-1
              .form-group
                %label Guests
                %i.fa.fa-user.infield
                = f.select :quantity, [1, 2, 3, 4], { selected: params[:quantity] }, class: 'total form-control', name: :quantity
            .col-sm-2
              %button.btn.btn-primary.btn-block{:type => "submit"}
                %i.fa.fa-plane
                Book
            .col-sm-12.text-center.text-danger
              %strong= params[:error]

app/views/shared/_header.html.haml
%header
  #sticky.yamm.navbar-default.border-btm
    .container.grad
      .navbar-header
        .h1
          Blue River Hotel
        .visible-xs-inline-block.pull-right.contact-mobile
          %a.white-color{:href => "tel:+84838376483"}
            .mobile-button.fa.fa-phone.text-center
          %a.white-color{:href => "mailto:blriverhotel@gmail.com"}
            .mobile-button.fa.fa-envelope.text-center
      #navbar-collapse-grid.navbar-collapse.collapse
        %ul.nav.navbar-nav
          %li.dropdown
            %a.dropdown-toggle.js-activated{"data-toggle" => "dropdown", :href => "#"}
              Accomodations
              %b.caret
            %ul.dropdown-menu
              - RoomType.find_each do |room|
                %li
                  = link_to room.name, room_path(room)
          %li.dropdown
            %a.dropdown-toggle.js-activated{"data-toggle" => "dropdown", :href => "#"}
              Promotions
              %b.caret
            %ul.dropdown-menu
              - Promotion.published.find_each do |promotion|
                %li
                  = link_to promotion.name, promotion_path(promotion)
            .dropdown-menu
          %li.dropdown
            %a.dropdown-toggle.js-activated{"data-toggle" => "dropdown", :href => "#"}
              Tours
              %b.caret
            %ul.dropdown-menu
              - Tour.find_each do |tour|
                %li
                  = link_to tour.name, tour_path(tour)
        .pull-right.white-color.contact-number
          .fa.fa-phone
          %a.white.hotel-tel{href: "tel:+84838376483"}
            +84 8 38376483
          %br
          .fa.fa-phone
          %a.white.hotel-tel{href: "tel:+84901604950"}
            +84 9 01604950
          %br
          .fa.fa-envelope
          %a.white.hotel-email{:href => "mailto:blriverhotel@gmail.com"}
            blriverhotel@gmail.com
        .pull-right.contact-btn.hidden-lg
          %a.white-color{:href => "tel:+84838376483"}
            .mobile-button.fa.fa-phone.text-center
          %a.white-color{:href => "mailto:blriverhotel@gmail.com"}
            .mobile-button.fa.fa-envelope.text-center

app/views/shared/_login_form.html.haml
#login-form
  %ul.nav.nav-tabs
    %li
      %a{:href => "#login", 'data-toggle' => :tab} Login
    %li
      %a{:href => "#register", 'data-toggle' => :tab} Register
  .tab-content
    #login.tab-pane.fade
      %h4.text-center Login With
      %br
      .social-buttons
        .btn.btn-primary.social-btn
          %span.fa.fa-facebook
            %strong Facebook
        .btn.btn-info.social-btn
          %span.fa.fa-twitter
            %strong Twitter
        .btn.btn-danger.social-btn
          %span.fa.fa-google
            %strong Google
      %br
      %hr
      %br
      = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
        .field
          = f.email_field :email, autofocus: true, placeholder: 'Email', class: 'form-control'
        %br
        .field
          = f.password_field :password, autocomplete: "off", placeholder: 'Password', class: 'form-control'
        - if devise_mapping.rememberable?
          .field
            .checkbox
              %label
                = f.check_box :remember_me
                Remember me
        .actions
          = f.submit "Log in", class: 'btn btn-success social-btn'
    #register.tab-pane.fade
      %h4.text-center Create Account
      %br
      = form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
        = devise_error_messages!
        .field
          = f.email_field :email, autofocus: true, placeholder: 'Email', class: 'form-control'
        %br
        .field
          = f.password_field :password, autocomplete: "off", placeholder: 'Password', class: 'form-control'
        %br
        .field
          = f.password_field :password_confirmation, autocomplete: "off", placeholder: 'Password Confirmation', class: 'form-control'
        %br
        .actions
          = f.submit "Register", class: 'btn btn-primary social-btn'
      %br
      = link_to "Forgot your password?", new_password_path(resource_name)

app/views/shared/_mobile_menu.html.haml
.col-xs-12#book-now-btn-mobile.grad
  .col-xs-6.hidden-md.hidden-lg#menu.dropup
    %a{href: '#', id: 'menu', 'data-toggle' => 'dropdown'}
      .h4.pull-left
        .fa.fa-bars.white-color
        .white-color.reserve-btn MENU
    %ul.dropdown-menu
      %li.dropdown-submenu
        %a{href: rooms_path} Accomodations
      - promotion = Promotion.published.last
      - if promotion
        %li
          %a{href: promotion_path(promotion)} #{promotion.name}
      %li
        %a{href: tours_path} Tours
  .col-xs-6.hidden-md.hidden-lg#book-now-btn.bookable{'data-room-id' => ''}
    .h4.pull-right
      .fa.fa-calendar.white-color
      .white-color.reserve-btn RESERVATION

app/views/shared/_review.html.haml
.row
  .col-xs-3.review-name #{name}
  .col-xs-9
    .progress.review
      .progress-bar.review.bold{style: "width: #{percentage}%"} #{percentage}%

app/views/shared/_reviews_chart.html.haml
.container.visible-xs.visible-sm
  .row
    %section.testimonials.mt50
      %h2.lined-heading
        %span Reviews from our Guests

  .row{style: 'margin-bottom: 20px'}
    .c100.p80.big.black.center
      %span 80%
      .slice
        .bar
        .fill
  -# - arr = [['Staff', 87], ['Cleanliness', 80],['Comfort', 75], ['Location', 86], ['Facilities', 74], ['Value for money', 80], ['Free Wifi', 81]]
  -# - arr.sort{|a, b| b.last <=> a.last}.each do |review|
  -#   = render 'shared/review', name: review.first, percentage: review.last

app/views/shared/_rooms.html.haml
%section.rooms.mt50
  .container
    .row
      .col-sm-12
        %h2.lined-heading
          %span #{title}
      / Room
      #room-carousel.carousel.slide.visible-md.visible-lg{'data-ride' => :carousel}
        %ol.carousel-indicators
          %li.carousel-dot{'data-target' => 'room-carousel', 'data-slide-to' => 0, class: :active, onClick: '$("#room-carousel").carousel(0);'}
          %li.carousel-dot{'data-target' => 'room-carousel', 'data-slide-to' => 1, onClick: '$("#room-carousel").carousel(1);'}
          %li.carousel-dot{'data-target' => 'room-carousel', 'data-slide-to' => 2, onClick: '$("#room-carousel").carousel(2);'}
        .carousel-inner
          = rooms.each_slice(3).each_with_index do |array_room, index|
            %div{class: (index == 0 ? 'item active': "item")}
              - array_room.each do |room_type|
                = render 'rooms/room', room_type: room_type, night: 1, quantity: 1
      .hidden-md.hidden-lg
        - RoomType.favourite.first(3).each do |room_type|
          = render 'rooms/room', room_type: room_type, night: 1, quantity: 1
      .clearfix
      %a{href: rooms_path}
        .text-center.black-color VIEW ALL

app/views/shared/_slidebox.html.haml
%section.gallery-slider.mt100
  .container
    .row
      .col-md-12
        %h2.lined-heading
          %span Gallery
  #owl-gallery.owl-carousel
    - RoomImage.find_each do |room_image|
      .item
        %a{href: room_image.image.url(:medium), class: :swipebox, rel: 'main-gallery'}
          = image_tag room_image.image.url(:medium), alt: room_image.room_type.name || 'Image'
          %i.fa.fa-search

app/views/shared/_top_header.html.haml
#top-header
  .container
    .row
      .col-xs-6
        .th-text.pull-left
          .th-item
            %a{:href => "#"}
              %i.fa.fa-phone
              05-460789986
          .th-item
            %a{:href => "#"}
              %i.fa.fa-envelope
              MAIL@STARHOTEL.COM
      .col-xs-6
        .th-text.pull-right
          .th-item
            .btn-group
              %button.btn.btn-default.btn-xs.dropdown-toggle.js-activated{"data-toggle" => "dropdown", :type => "button"}
                English
                %span.caret
              %ul.dropdown-menu
                %li
                  %a{:href => "#"} ENGLISH
                %li
                  %a{:href => "#"} FRANCE
                %li
                  %a{:href => "#"} GERMAN
                %li
                  %a{:href => "#"} SPANISH
          .th-item
            .social-icons
              %a{:href => "#"}
                %i.fa.fa-facebook
              %a{:href => "#"}
                %i.fa.fa-twitter
              %a{:href => "#"}
                %i.fa.fa-youtube-play