config/routes.rb
Rails.application.routes.draw do
require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'homes#show'
  post 'set_time', to: 'homes#set_time'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    get 'login', to: 'sessions#new'
    get 'logout', to: 'sessions#logout'
    resources :sessions
    resources :rooms
    resources :room_types
    resources :landing_images do
      get :resize, on: :collection
    end
    resources :tours
    resources :review_images

    resource :main
    resources :contacts, only: :index do
      post :upload, on: :collection
    end

    resource :amenities
    resources :promotions
  end
  resource :home, only: :show do
    get :show2, on: :member
    get :test, on: :member
  end

  resources :rooms, only: [:show, :index]
  resource :paypal, only: :show do
    get :success, on: :member
    get :failed, on: :member
  end

  resources :amenities, only: :index
  resources :availables, only: :create
  resources :tours, only: [:index, :show]
  resources :promotions, only: :show

end

app/models/promotion.rb
class Promotion < ApplicationRecord
  include FriendlyId
  friendly_id :name, use: :slugged
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  scope :published, -> { where(published: true) }

  def discount
    if percentage_off.present?
      "#{percentage_off}%"
    else
      amount_off
      "$#{percentage_off}"
    end
  end
  private
  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end
end

app/controllers/admin/promotions_controller.rb
class Admin::PromotionsController < AdminController
  def index

  end

  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.new(promotion_params)
    if @promotion.save
      redirect_to action: :index
    else
      flash.now[:danger] = @promotion.errors
      render :new
    end
  end

  def edit
    @promotion = Promotion.friendly.find(params[:id])
  end

  def update
    @promotion = Promotion.friendly.find(params[:id])
    if @promotion.update_attributes(promotion_params)
      redirect_to action: :edit
    else
      flash.now[:danger] = @promotion.errors
      render :edit
    end

  end

  def destroy
    Promotion.friendly.find(params[:id]).destroy
    redirect_to action: :index
  end

  private
  def promotion_params
    params.require(:promotion).permit(:name, :code, :percentage_off, :amount_off, :image, :start_time, :end_time, :description, :published)
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  def show
    @promotion = Promotion.friendly.find(params[:id])
  end
end

app/views/admin/promotions/_form.html.haml
%h1.text-center Admin Promotions
.container
  = render 'shared/flash'
  = form_for [:admin, @promotion] do |f|
    = f.hidden_field :id
    .form-group
      = f.label :image, class: 'control-label'
      = link_to image_tag(f.object.image.url(:medium)), f.object.image.url(:original) if f.object.image?
      = f.file_field :image
    .form-group
      = f.label :name, class: 'control-label'
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :percentage_off, class: 'control-label'
      = f.text_field :percentage_off, class: 'form-control'
    .form-group
      = f.label :amount_off, class: 'control-label'
      = f.text_field :amount_off, class: 'form-control'
    .form-group
      = f.label :code, class: 'control-label'
      = f.text_field :code, class: 'form-control'
    .form-group
      = f.label :start_time, class: 'control-label'
      = f.text_field :start_time, class: 'form-control date-picker'
    .form-group
      = f.label :end_time, class: 'control-label'
      = f.text_field :end_time, class: 'form-control date-picker'
    .form-group
      = f.label :published, class: 'control-label'
      = f.check_box :published
    .form-group
      = f.label :description, class: 'control-label'
      = f.text_area :description, class: 'form-control'
    = f.submit class: 'btn btn-primary'
:javascript
  $('.date-picker').datepicker({format: 'yyyy-mm-dd'});

app/views/admin/promotions/edit.html.haml
= render 'form'

app/views/admin/promotions/index.html.haml
%h1.text-center
  Admin Promotions
.container-fluid
  .row
    %h3.col-md-2.text-center
      Name
    %h3.col-md-1.text-center
      #{"% Off"}
    %h3.col-md-1.text-center
      Amount Off
    %h3.col-md-2.text-center
      Code
    %h3.col-md-2.text-center
      Start
    %h3.col-md-2.text-center
      End
    %h3.col-md-2.text-center
      Actions
  - Promotion.find_each do |promotion|
    .row.promotion
      .col-md-2.text-center
        = promotion.name
      .col-md-1.text-center
        = promotion.percentage_off
      .col-md-1.text-center
        = promotion.amount_off
      .col-md-2.text-center
        = promotion.code
      .col-md-2.text-center
        = promotion.start_time
      .col-md-2.text-center
        = promotion.end_time
      .col-md-2.text-center
        = link_to 'Delete', admin_promotion_path(promotion), method: :delete, data: {confirm: 'Are you sure ?'}
        = link_to 'Edit', edit_admin_promotion_path(promotion)
  .text-center
    %br
    = link_to 'Add New Image', new_admin_promotion_path, class: 'btn btn-success'

app/views/admin/promotions/new.html.haml
= render 'form'